"""Initial migration

Revision ID: 6f793d461b10
Revises: 
Create Date: 2025-12-28 20:16:04.129386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f793d461b10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tsv'), table_name='users', postgresql_using='gin')
    op.create_index('ix_user_tsv', 'users', [sa.literal_column("to_tsvector('english', username || ' ' || email || ' ' || full_name)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.create_index(op.f('ix_user_tsv'), 'users', [sa.literal_column("to_tsvector('english'::regconfig, (((username::text || ' '::text) || email::text) || ' '::text) || full_name::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
